version: '3.8'

services:
  # 1. MySQL (保持不变，它比较皮实)
  db_mysql:
    image: mysql:8.0
    container_name: medical_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: RootPassword123!
      MYSQL_DATABASE: region_a_db
    ports:
      - "33061:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  # 2. PostgreSQL (保持不变)
  db_pg:
    image: postgres:14
    container_name: medical_pg
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: RootPassword123!
      POSTGRES_DB: region_b_db
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  # 3. SQL Server (重大修改：改用 Named Volume)
  db_mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: medical_mssql
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: RootPassword123!
    ports:
      - "14330:1433"
    volumes:
      # 注意这里！不再指向 ./data/mssql，而是指向下面的 mssql_data
      - mssql_data:/var/opt/mssql

# 在文件最底部添加这个
volumes:
  mssql_data: