version: '3.8'

services:
  # 1. MySQL (模拟分院 A)
  db_mysql:
    image: mysql:8.0
    container_name: medical_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: RootPassword123!
      MYSQL_DATABASE: region_a_db
      TZ: Asia/Shanghai  # 【修改】设置时区
    ports:
      - "33061:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  # 2. PostgreSQL (模拟分院 B)
  db_pg:
    image: postgres:14
    container_name: medical_pg
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: RootPassword123!
      POSTGRES_DB: region_b_db
      TZ: Asia/Shanghai  # 【修改】设置时区
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  # 3. SQL Server (模拟集团总库)
  db_mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: medical_mssql
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: RootPassword123!
      TZ: Asia/Shanghai  # 【修改】设置时区
    ports:
      - "14330:1433"
    volumes:
      - mssql_data:/var/opt/mssql

volumes:
  mssql_data: